const Discord = require('discord.js');
const filterLevels = ['Off', 'No Role', 'Everyone'];
const verificationLevels = ['None', 'Low', 'Medium', '(╯°□°）╯︵ ┻━┻', '┻━┻ ﾐヽ(ಠ益ಠ)ノ彡┻━┻'];
const checkBots = require('../util/functions.js');
const check = require('../util/functions.js');

exports.run = async function(client, message, args) {
  console.log(message.author.presence);
  if (!message.guild.members.has(message.guild.ownerID)) await message.guild.members.fetch(message.guild.ownerID);
  const strmCount = message.guild.members.filter(m => m.user.presence && m.user.presence === 'STREAMING');
  const embed = new Discord.RichEmbed()
    .setAuthor(`${message.guild.name} - Server Information`, message.guild.iconURL)
    .setColor(0x00AE86)
  // Displays the guild icon on the right side, commented it out cause I don't like it.
  //.setThumbnail(message.guild.iconURL)
    .addField('❯ Name', message.guild.name, true)
    .addField('❯ ID', message.guild.id, true)
    .addField('❯ Region', message.guild.region.toUpperCase(), true)
    .addField('❯ Creation Date', message.guild.createdAt.toDateString(), true)
    .addField('❯ Explicit Filter', filterLevels[message.guild.explicitContentFilter], true)
    .addField('❯ Verification Level', verificationLevels[message.guild.verificationLevel], true)
    .addField('❯ Owner', message.guild.owner.user.tag, true)
    .addField('❯ Roles', message.guild.roles.size, true)
    .addField('❯ Channels', message.guild.channels.size, true)
    .addField('❯ Members',`\`${check.checkMembers(message.guild)}\` Members | \`${check.checkBots(message.guild)}\` Bots | Total \`${message.guild.memberCount}\` \n <a:online:505062424798429196> \`${check.checkMembersOnline(message.guild)}\` <a:idle:505062424626462740> \`${check.checkMembersIdle(message.guild)}\` <a:dnd:505062424437719060> \`${check.checkMembersDND(message.guild)}\` <a:streaming:505062420079968256> \`${strmCount.size}\` <a:offline:505062424638914560> \`${check.checkMembersOffline(message.guild)}\``)
    .setFooter(`Generated by ${message.author.username}#${message.author.discriminator}`, message.author.avatarURL)
    .setTimestamp();
  message.channel.send({embed});



};

exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: ['serverinfo'],
  permLevel: 'User'
};

exports.help = {
  name: 'server',
  category: 'Misc',
  description: 'Shows information about the server',
  usage: 'server'
};
